version: '3.9'
services:
  test-backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      # TODO conditionをつける
      - test-postgres
      - test-redis
    networks:
      - test-backend

  test-postgres:
    restart: always
    image: postgres:latest
    environment:
    # if not POSTGRES_USER and POSTGRES_DB, it will be "postgres".
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - test-backend

  test-redis:
    restart: always
    image: "redis:latest"
    ports:
      - 6379:6379
    volumes:
      - ./tmp/cache:/var/lib/redis/data
    networks:
      - test-backend

networks:
  test-backend:
    driver: bridge
    external: true